version: "3.9"

services:
    pgDatabase:
     image: postgres:13
     environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ny_taxi
     volumes:
       - ./ny_taxi_postgres_data:/var/lib/postgresql/data:rw
     ports:
         - 5432:5432
    pgAdmin:
     image: dpage/pgadmin4
     environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
     ports:
         - 8080:80